[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "VITE_ELEVENLAB_KEY,VITE_STRIPE_PUBLISHABLE_KEY,VITE_PAYPAL_CLIENT_ID,VITE_PAYPAL_CLIENT_ID_TEST,VITE_PAYPAL_PLAN_ELITE_MONTHLY_ID,VITE_PAYPAL_PLAN_ELITE_MONTHLY_ID_TEST,VITE_PAYPAL_PLAN_ELITE_YEARLY_ID,VITE_PAYPAL_PLAN_ELITE_YEARLY_ID_TEST,VITE_PAYPAL_PLAN_PRO_MONTHLY_ID,VITE_PAYPAL_PLAN_PRO_MONTHLY_ID_TEST,VITE_PAYPAL_PLAN_PRO_YEARLY_ID,VITE_PAYPAL_PLAN_PRO_YEARLY_ID_TEST,VITE_SQUARE_APPLICATION_ID,VITE_SQUARE_ENVIRONMENT,VITE_PAYPAL_ENVIRONMENT,VITE_EDITOR_URL,VITE_SOLANA_RPC_URL,VITE_MERCHANT_WALLET"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
