import { Link } from "react-router-dom";
import { ArrowLeft } from "lucide-react";
import { useI18n } from "../i18n/i18n-context";
import LanguageSelector from "../i18n/language-selector";
import SEO from "../components/seo";

function Section({ number, title, children }) {
  return (
    <div className="space-y-3">
      <h2 className="text-xl font-semibold text-white flex items-baseline gap-2">
        <span className="text-[#DC569D] font-mono text-sm">{number}.</span>
        {title}
      </h2>
      <div className="text-gray-400 leading-relaxed space-y-3 pl-0 md:pl-6">
        {children}
      </div>
    </div>
  );
}

function SubSection({ number, title, children }) {
  return (
    <div className="space-y-2 mt-4">
      <h3 className="text-base font-medium text-gray-200">
        <span className="text-gray-500 font-mono text-sm mr-1">{number}</span>
        {title}
      </h3>
      <div className="text-gray-400 leading-relaxed space-y-2">{children}</div>
    </div>
  );
}

const content = {
  en: {
    back: "Back to Home",
    badge: "Legal",
    title: "Terms & Conditions",
    effective: "Effective: 12/08/2025",
    updated: "Last Updated: 12/08/2025",
    intro1: (
      <>
        These Terms and Conditions constitute a legally binding agreement
        between you (the "User") and{" "}
        <strong className="text-white">Reel Me In Media Limited</strong>,
        registered in London, United Kingdom, trading as{" "}
        <strong className="text-white">Reelmotion AI</strong>, governing your
        access to and use of the Reelmotion AI platform, website, applications,
        and related services ("Reelmotion AI").
      </>
    ),
    intro2:
      "By using our Platform, you agree to these Terms. If you do not agree, you must stop using the Platform immediately.",
    s1: "Definitions",
    s1p: "For the purposes of these Terms:",
    s1items: [
      <><strong className="text-gray-200">"Content"</strong> means any data, images, video, audio, text, graphics, code, or other materials uploaded, generated, or transmitted via the Platform.</>,
      <><strong className="text-gray-200">"AI Output"</strong> refers to any video, image, or media generated by the Platform's artificial intelligence tools based on your inputs or prompts.</>,
      <><strong className="text-gray-200">"User Content"</strong> means all Content provided by you, including media you upload for processing.</>,
      <><strong className="text-gray-200">"Prohibited Content"</strong> means material that violates these Terms or applicable laws, including but not limited to: nudity, sexual material, hate speech, discriminatory content, harassment, extreme violence, incitement, misinformation, and unlawful impersonation.</>,
    ],
    s2: "Eligibility",
    s2p: "You must:",
    s2items: [
      "Be at least 13 years old. If under the age of majority in your jurisdiction, you must have parental/guardian consent.",
      "Have the legal capacity to enter into binding contracts.",
      "Not be located in a country or territory subject to UK, US, or EU sanctions.",
    ],
    s3: "User Responsibilities",
    s3p: "When using the Platform, you agree to:",
    s3items: [
      "Provide accurate account information and keep it updated.",
      "Comply with all applicable laws in your jurisdiction.",
    ],
    s3misuse: [
      "Uploading, creating, or sharing Prohibited Content.",
      "Using the Platform to create misleading or harmful AI deepfakes or to impersonate individuals without consent.",
      "Uploading content you do not own or have rights to use.",
      "Attempting to reverse-engineer, hack, or disrupt the Platform's functionality.",
    ],
    s3note: "We reserve the right to suspend or terminate your account if we believe you have breached these Terms.",
    s4: "Content Standards",
    s4p: "You must not submit, generate, or distribute content that:",
    s4items: [
      "Contains nudity, sexual acts, or pornographic material.",
      "Depicts extreme violence or gore.",
      "Promotes hate speech, racism, sexism, or other discriminatory ideologies.",
      "Harasses, bullies, or threatens others.",
      "Violates intellectual property rights, including copyrighted or trademarked works, without permission.",
      "Uses real individuals' faces, voices, or likenesses without consent, especially in a false, defamatory, or incriminating manner.",
    ],
    s5: "User Content & AI Output Licensing",
    s5p: "By using the Platform, you:",
    s5items: [
      "Retain ownership of your User Content and AI Output.",
      "Acknowledge that we may disclose content to law enforcement or government authorities if required by law.",
    ],
    s5license: [
      "Store and process your content for service delivery.",
      "Use your content for internal research, AI model improvement, and quality assurance.",
      "Display your content as marketing examples for the Platform (unless you opt-out via written notice).",
    ],
    s5licenseIntro: "Grant us a non-exclusive, worldwide, royalty-free, perpetual license to:",
    s6: "Payments & Refunds",
    s6items: [
      "The Platform is provided on a pay-per-use basis.",
      "All payments are final and non-refundable, except where required by law.",
      "You are responsible for any applicable taxes, duties, and charges.",
      "We reserve the right to change pricing at any time, with changes applying to future transactions.",
    ],
    s7: "Intellectual Property Rights",
    s7items: [
      "All software, algorithms, trademarks, branding, and platform designs are the exclusive property of Reel Me In Media Limited.",
      "You may not copy, distribute, modify, or create derivative works from our intellectual property without prior written permission.",
    ],
    s8: "Service Availability & Disclaimers",
    s8items: [
      'The Platform is provided "as is" and "as available".',
      "We make no warranties about uninterrupted operation, error-free functionality, or that results will meet your expectations.",
      "AI-generated content is produced algorithmically and may contain inaccuracies or unintended results. You are solely responsible for reviewing and ensuring the legality of outputs before use.",
    ],
    s9: "Limitation of Liability",
    s9p: "To the fullest extent permitted by law:",
    s9items: [
      "We are not liable for indirect, incidental, special, or consequential damages.",
      "Our total liability in any claim is limited to the total amount you paid for Platform access in the preceding three (3) months.",
    ],
    s10: "Termination",
    s10p: "We may suspend or terminate your account at any time if you:",
    s10items: [
      "Breach these Terms.",
      "Use the Platform for unlawful purposes.",
      "Engage in conduct that could harm us, our users, or third parties.",
    ],
    s11: "Dispute Resolution",
    s11items: [
      "Disputes shall be resolved exclusively through binding arbitration in London, United Kingdom.",
      "Arbitration will be conducted in English under the rules of the London Court of International Arbitration (LCIA).",
      "You waive the right to participate in class actions or consolidated proceedings.",
    ],
    s12: "Affiliate Program Terms",
    s12_1: "Eligibility",
    s12_1p: 'By creating a profile on Reelmotion AI (the "Platform"), you are automatically enrolled in our Affiliate Program ("Program"). Participation in the Program is conditional upon compliance with these Terms & Conditions. We reserve the right to refuse or terminate participation at any time at our sole discretion.',
    s12_2: "Affiliate Links",
    s12_2p: 'Each registered user will be provided with a unique referral link ("Affiliate Link"). You may share this link to promote our services/products. Any sales generated through your Affiliate Link will be tracked and attributed to you through our system.',
    s12_3: "Commission & Payments",
    s12_3items: [
      "Affiliates earn a 10% commission on every purchase made by customers who signed up or were introduced through their Affiliate Link.",
      "This commission applies to all future purchases made by those referred customers for as long as the customer remains active, unless the Program or Platform is terminated.",
      "No commissions will be earned for profile creations or sign-ups without purchase.",
      "Payments will be made bimonthly (every two months) via PayPal, bank transfer, or cryptocurrency transfer, depending on the Affiliate's selected payment method.",
      "Commissions will only be paid on valid, completed purchases that are not canceled, refunded, or disputed.",
      "A minimum payout threshold of USD $50 applies.",
      "Any transfer fees (e.g., bank or crypto network fees) may be deducted from the payout.",
    ],
    s12_4: "Prohibited Activities",
    s12_4p: "Affiliates are strictly prohibited from:",
    s12_4items: [
      "Engaging in misleading, false, or deceptive marketing practices.",
      "Using paid advertising (including search engine ads) that compete with Reel Me In Media's own advertising.",
      "Promoting the Platform on websites or channels that contain unlawful, harmful, or offensive content.",
      "Spamming or sending unsolicited communications.",
    ],
    s12_4note: "Violation of these rules may result in forfeiture of commissions and termination from the Program.",
    s12_5: "Intellectual Property",
    s12_5p: "You are granted a limited, non-exclusive, revocable license to use our brand name, trademarks, and promotional materials solely for the purpose of promoting the Platform through your Affiliate Link. All rights not expressly granted remain reserved by Reel Me In Media Limited.",
    s12_6: "Relationship of Parties",
    s12_6p: "Nothing in these Terms shall create any partnership, joint venture, employment, or agency relationship between you and Reel Me In Media. You act as an independent contractor in promoting the Platform.",
    s12_7: "Termination",
    s12_7p: "We reserve the right to suspend or terminate your participation in the Program at any time, with or without cause, and without prior notice. Upon termination, any unpaid commissions may be forfeited at our discretion.",
    s12_8: "Limitation of Liability",
    s12_8p: "Reel Me In Media will not be liable for indirect, incidental, or consequential damages related to your participation in the Program. Our total liability shall not exceed the total commissions paid to you in the last 6 months.",
    s12_9: "Amendments",
    s12_9p: "We may modify these Terms at any time. Continued participation in the Program after changes take effect constitutes acceptance of the updated Terms.",
    s13: "Governing Law",
    s13p: "These Terms shall be governed by and construed in accordance with the laws of England and Wales, without regard to conflict-of-law principles.",
    s14: "Changes to Terms",
    s14p: "We may amend these Terms at any time by posting an updated version on our Platform. Continued use of the Platform after changes take effect constitutes acceptance of the updated Terms.",
    s15: "Contact Information",
    s15p: "If you have questions about these Terms, contact us:",
    footer: "By using Reelmotion AI, you acknowledge that you have read, understood, and agree to be bound by these Terms and Conditions.",
  },
  es: {
    back: "Volver al Inicio",
    badge: "Legal",
    title: "Términos y Condiciones",
    effective: "Vigencia: 12/08/2025",
    updated: "Última actualización: 12/08/2025",
    intro1: (
      <>
        Estos Términos y Condiciones constituyen un acuerdo legalmente vinculante
        entre usted (el "Usuario") y{" "}
        <strong className="text-white">Reel Me In Media Limited</strong>,
        registrada en Londres, Reino Unido, operando como{" "}
        <strong className="text-white">Reelmotion AI</strong>, que rige su
        acceso y uso de la plataforma, sitio web, aplicaciones y servicios
        relacionados de Reelmotion AI.
      </>
    ),
    intro2:
      "Al usar nuestra Plataforma, usted acepta estos Términos. Si no está de acuerdo, debe dejar de usar la Plataforma inmediatamente.",
    s1: "Definiciones",
    s1p: "A los efectos de estos Términos:",
    s1items: [
      <><strong className="text-gray-200">"Contenido"</strong> significa cualquier dato, imagen, video, audio, texto, gráfico, código u otro material subido, generado o transmitido a través de la Plataforma.</>,
      <><strong className="text-gray-200">"Salida de IA"</strong> se refiere a cualquier video, imagen o medio generado por las herramientas de inteligencia artificial de la Plataforma basado en sus entradas o prompts.</>,
      <><strong className="text-gray-200">"Contenido del Usuario"</strong> significa todo el Contenido proporcionado por usted, incluyendo medios que suba para procesamiento.</>,
      <><strong className="text-gray-200">"Contenido Prohibido"</strong> significa material que viola estos Términos o las leyes aplicables, incluyendo pero no limitado a: desnudez, material sexual, discurso de odio, contenido discriminatorio, acoso, violencia extrema, incitación, desinformación y suplantación ilegal de identidad.</>,
    ],
    s2: "Elegibilidad",
    s2p: "Usted debe:",
    s2items: [
      "Tener al menos 13 años. Si es menor de edad en su jurisdicción, debe contar con el consentimiento de sus padres/tutores.",
      "Tener la capacidad legal para celebrar contratos vinculantes.",
      "No estar ubicado en un país o territorio sujeto a sanciones del Reino Unido, EE.UU. o la UE.",
    ],
    s3: "Responsabilidades del Usuario",
    s3p: "Al usar la Plataforma, usted acepta:",
    s3items: [
      "Proporcionar información de cuenta precisa y mantenerla actualizada.",
      "Cumplir con todas las leyes aplicables en su jurisdicción.",
    ],
    s3misuse: [
      "Subir, crear o compartir Contenido Prohibido.",
      "Usar la Plataforma para crear deepfakes de IA engañosos o dañinos o para suplantar la identidad de personas sin consentimiento.",
      "Subir contenido que no le pertenece o para el cual no tiene derechos de uso.",
      "Intentar realizar ingeniería inversa, hackear o interrumpir la funcionalidad de la Plataforma.",
    ],
    s3note: "Nos reservamos el derecho de suspender o cancelar su cuenta si creemos que ha incumplido estos Términos.",
    s4: "Estándares de Contenido",
    s4p: "No debe enviar, generar ni distribuir contenido que:",
    s4items: [
      "Contenga desnudez, actos sexuales o material pornográfico.",
      "Represente violencia extrema o gore.",
      "Promueva discurso de odio, racismo, sexismo u otras ideologías discriminatorias.",
      "Acose, intimide o amenace a otros.",
      "Viole derechos de propiedad intelectual, incluyendo obras con derechos de autor o marcas registradas, sin permiso.",
      "Use rostros, voces o semejanzas de personas reales sin consentimiento, especialmente de manera falsa, difamatoria o incriminatoria.",
    ],
    s5: "Licencia de Contenido del Usuario y Salida de IA",
    s5p: "Al usar la Plataforma, usted:",
    s5items: [
      "Conserva la propiedad de su Contenido de Usuario y Salida de IA.",
      "Reconoce que podemos divulgar contenido a las autoridades legales o gubernamentales si así lo requiere la ley.",
    ],
    s5license: [
      "Almacenar y procesar su contenido para la prestación del servicio.",
      "Usar su contenido para investigación interna, mejora de modelos de IA y garantía de calidad.",
      "Mostrar su contenido como ejemplos de marketing para la Plataforma (a menos que opte por no hacerlo mediante aviso escrito).",
    ],
    s5licenseIntro: "Nos otorga una licencia no exclusiva, mundial, libre de regalías y perpetua para:",
    s6: "Pagos y Reembolsos",
    s6items: [
      "La Plataforma se proporciona en base a pago por uso.",
      "Todos los pagos son finales y no reembolsables, excepto cuando lo exija la ley.",
      "Usted es responsable de cualquier impuesto, arancel y cargo aplicable.",
      "Nos reservamos el derecho de cambiar los precios en cualquier momento, aplicando los cambios a transacciones futuras.",
    ],
    s7: "Derechos de Propiedad Intelectual",
    s7items: [
      "Todo el software, algoritmos, marcas registradas, branding y diseños de la plataforma son propiedad exclusiva de Reel Me In Media Limited.",
      "No puede copiar, distribuir, modificar ni crear obras derivadas de nuestra propiedad intelectual sin permiso previo por escrito.",
    ],
    s8: "Disponibilidad del Servicio y Descargos",
    s8items: [
      'La Plataforma se proporciona "tal cual" y "según disponibilidad".',
      "No ofrecemos garantías sobre operación ininterrumpida, funcionalidad libre de errores, ni que los resultados cumplan con sus expectativas.",
      "El contenido generado por IA se produce algorítmicamente y puede contener inexactitudes o resultados no deseados. Usted es el único responsable de revisar y asegurar la legalidad de los resultados antes de su uso.",
    ],
    s9: "Limitación de Responsabilidad",
    s9p: "En la máxima medida permitida por la ley:",
    s9items: [
      "No somos responsables de daños indirectos, incidentales, especiales o consecuentes.",
      "Nuestra responsabilidad total en cualquier reclamo se limita al monto total que usted pagó por el acceso a la Plataforma en los tres (3) meses anteriores.",
    ],
    s10: "Terminación",
    s10p: "Podemos suspender o cancelar su cuenta en cualquier momento si usted:",
    s10items: [
      "Incumple estos Términos.",
      "Usa la Plataforma para fines ilegales.",
      "Participa en conductas que puedan perjudicarnos a nosotros, a nuestros usuarios o a terceros.",
    ],
    s11: "Resolución de Disputas",
    s11items: [
      "Las disputas se resolverán exclusivamente mediante arbitraje vinculante en Londres, Reino Unido.",
      "El arbitraje se llevará a cabo en inglés bajo las reglas de la Corte de Arbitraje Internacional de Londres (LCIA).",
      "Usted renuncia al derecho de participar en acciones colectivas o procedimientos consolidados.",
    ],
    s12: "Términos del Programa de Afiliados",
    s12_1: "Elegibilidad",
    s12_1p: 'Al crear un perfil en Reelmotion AI (la "Plataforma"), usted se inscribe automáticamente en nuestro Programa de Afiliados ("Programa"). La participación está condicionada al cumplimiento de estos Términos y Condiciones. Nos reservamos el derecho de rechazar o terminar la participación en cualquier momento a nuestra entera discreción.',
    s12_2: "Enlaces de Afiliado",
    s12_2p: 'A cada usuario registrado se le proporcionará un enlace de referencia único ("Enlace de Afiliado"). Puede compartir este enlace para promocionar nuestros servicios/productos. Las ventas generadas a través de su Enlace de Afiliado serán rastreadas y atribuidas a usted.',
    s12_3: "Comisiones y Pagos",
    s12_3items: [
      "Los afiliados ganan una comisión del 10% en cada compra realizada por clientes que se registraron o fueron presentados a través de su Enlace de Afiliado.",
      "Esta comisión aplica a todas las compras futuras de esos clientes referidos mientras permanezcan activos, a menos que el Programa o la Plataforma se terminen.",
      "No se ganarán comisiones por creaciones de perfil o registros sin compra.",
      "Los pagos se realizarán bimestralmente vía PayPal, transferencia bancaria o criptomoneda, según el método seleccionado por el Afiliado.",
      "Las comisiones solo se pagarán por compras válidas y completadas que no sean canceladas, reembolsadas o disputadas.",
      "Aplica un umbral mínimo de pago de USD $50.",
      "Las tarifas de transferencia (por ejemplo, bancarias o de red cripto) pueden deducirse del pago.",
    ],
    s12_4: "Actividades Prohibidas",
    s12_4p: "Los afiliados tienen estrictamente prohibido:",
    s12_4items: [
      "Participar en prácticas de marketing engañosas, falsas o fraudulentas.",
      "Usar publicidad paga (incluidos anuncios en motores de búsqueda) que compita con la publicidad propia de Reel Me In Media.",
      "Promocionar la Plataforma en sitios web o canales que contengan contenido ilegal, dañino u ofensivo.",
      "Enviar spam o comunicaciones no solicitadas.",
    ],
    s12_4note: "La violación de estas reglas puede resultar en la pérdida de comisiones y la terminación del Programa.",
    s12_5: "Propiedad Intelectual",
    s12_5p: "Se le otorga una licencia limitada, no exclusiva y revocable para usar nuestro nombre de marca, marcas registradas y materiales promocionales únicamente con el propósito de promocionar la Plataforma a través de su Enlace de Afiliado. Todos los derechos no otorgados expresamente permanecen reservados por Reel Me In Media Limited.",
    s12_6: "Relación entre las Partes",
    s12_6p: "Nada en estos Términos creará ninguna asociación, empresa conjunta, relación laboral o de agencia entre usted y Reel Me In Media. Usted actúa como contratista independiente en la promoción de la Plataforma.",
    s12_7: "Terminación",
    s12_7p: "Nos reservamos el derecho de suspender o terminar su participación en el Programa en cualquier momento, con o sin causa, y sin previo aviso. Tras la terminación, cualquier comisión impaga puede ser confiscada a nuestra discreción.",
    s12_8: "Limitación de Responsabilidad",
    s12_8p: "Reel Me In Media no será responsable de daños indirectos, incidentales o consecuentes relacionados con su participación en el Programa. Nuestra responsabilidad total no excederá el total de comisiones pagadas a usted en los últimos 6 meses.",
    s12_9: "Modificaciones",
    s12_9p: "Podemos modificar estos Términos en cualquier momento. La participación continua en el Programa después de que los cambios entren en vigor constituye la aceptación de los Términos actualizados.",
    s13: "Ley Aplicable",
    s13p: "Estos Términos se regirán e interpretarán de acuerdo con las leyes de Inglaterra y Gales, sin tener en cuenta los principios de conflicto de leyes.",
    s14: "Cambios a los Términos",
    s14p: "Podemos modificar estos Términos en cualquier momento publicando una versión actualizada en nuestra Plataforma. El uso continuado de la Plataforma después de que los cambios entren en vigor constituye la aceptación de los Términos actualizados.",
    s15: "Información de Contacto",
    s15p: "Si tiene preguntas sobre estos Términos, contáctenos:",
    footer: "Al usar Reelmotion AI, usted reconoce que ha leído, comprendido y acepta estar sujeto a estos Términos y Condiciones.",
  },
};

export default function TermsPage() {
  const { locale } = useI18n();
  const t = content[locale] || content.en;

  return (
    <div className="bg-[#0C0C0D] text-white">
      <SEO
        title="Terms of Service — Reelmotion AI"
        description="Terms of Service for Reelmotion AI. Read our terms and conditions for using the AI video, image, and audio generation platform."
        url="https://reelmotion.ai/terms"
        lang={locale}
      />
      {/* Top bar */}
      <div className="sticky top-0 z-10 border-b border-white/5 bg-[#0C0C0D]/95 backdrop-blur-sm">
        <div className="max-w-3xl mx-auto px-6 py-4 flex items-center justify-between">
          <Link
            to="/"
            className="flex items-center gap-2 text-gray-500 hover:text-white transition-colors text-sm"
          >
            <ArrowLeft size={16} />
            {t.back}
          </Link>
          <LanguageSelector />
        </div>
      </div>

      {/* Header */}
      <div className="max-w-3xl mx-auto px-6 pt-16 pb-10">
        <div className="flex items-center gap-3 mb-6">
          <img src="/logos/logo_reelmotion_new.webp" alt="Reelmotion AI" className="h-8" />
          <span className="text-xs font-mono text-gray-600 uppercase tracking-widest">{t.badge}</span>
        </div>
        <h1 className="text-4xl md:text-5xl font-bold tracking-tight mb-4">{t.title}</h1>
        <div className="flex items-center gap-4 text-sm text-gray-600 font-mono">
          <span>{t.effective}</span>
          <span className="w-1 h-1 rounded-full bg-gray-700" />
          <span>{t.updated}</span>
        </div>
        <div className="h-px w-full mt-10" style={{ background: "linear-gradient(to right, rgba(220,86,157,0.3), transparent)" }} />
      </div>

      {/* Content */}
      <div className="max-w-3xl mx-auto px-6 pb-24 space-y-10">
        <p className="text-gray-400 leading-relaxed">{t.intro1}</p>
        <p className="text-gray-400 leading-relaxed">{t.intro2}</p>

        <Section number="1" title={t.s1}>
          <p>{t.s1p}</p>
          <ul className="list-disc ml-6 space-y-2">{t.s1items.map((item, i) => <li key={i}>{item}</li>)}</ul>
        </Section>

        <Section number="2" title={t.s2}>
          <p>{t.s2p}</p>
          <ul className="list-disc ml-6 space-y-2">{t.s2items.map((item, i) => <li key={i}>{item}</li>)}</ul>
        </Section>

        <Section number="3" title={t.s3}>
          <p>{t.s3p}</p>
          <ol className="list-decimal ml-6 space-y-2">
            {t.s3items.map((item, i) => <li key={i}>{item}</li>)}
            <li>
              Not misuse the Platform:
              <ul className="list-disc ml-6 mt-2 space-y-1">
                {t.s3misuse.map((item, i) => <li key={i}>{item}</li>)}
              </ul>
            </li>
          </ol>
          <p>{t.s3note}</p>
        </Section>

        <Section number="4" title={t.s4}>
          <p>{t.s4p}</p>
          <ul className="list-disc ml-6 space-y-2">{t.s4items.map((item, i) => <li key={i}>{item}</li>)}</ul>
        </Section>

        <Section number="5" title={t.s5}>
          <p>{t.s5p}</p>
          <ul className="list-disc ml-6 space-y-2">
            <li>{t.s5items[0]}</li>
            <li>
              {t.s5licenseIntro}
              <ul className="list-disc ml-6 mt-2 space-y-1">
                {t.s5license.map((item, i) => <li key={i}>{item}</li>)}
              </ul>
            </li>
            <li>{t.s5items[1]}</li>
          </ul>
        </Section>

        <Section number="6" title={t.s6}>
          <ul className="list-disc ml-6 space-y-2">{t.s6items.map((item, i) => <li key={i}>{item}</li>)}</ul>
        </Section>

        <Section number="7" title={t.s7}>
          <ul className="list-disc ml-6 space-y-2">{t.s7items.map((item, i) => <li key={i}>{item}</li>)}</ul>
        </Section>

        <Section number="8" title={t.s8}>
          <ul className="list-disc ml-6 space-y-2">{t.s8items.map((item, i) => <li key={i}>{item}</li>)}</ul>
        </Section>

        <Section number="9" title={t.s9}>
          <p>{t.s9p}</p>
          <ul className="list-disc ml-6 space-y-2">{t.s9items.map((item, i) => <li key={i}>{item}</li>)}</ul>
        </Section>

        <Section number="10" title={t.s10}>
          <p>{t.s10p}</p>
          <ul className="list-disc ml-6 space-y-2">{t.s10items.map((item, i) => <li key={i}>{item}</li>)}</ul>
        </Section>

        <Section number="11" title={t.s11}>
          <ul className="list-disc ml-6 space-y-2">{t.s11items.map((item, i) => <li key={i}>{item}</li>)}</ul>
        </Section>

        <Section number="12" title={t.s12}>
          <SubSection number="12.1" title={t.s12_1}><p>{t.s12_1p}</p></SubSection>
          <SubSection number="12.2" title={t.s12_2}><p>{t.s12_2p}</p></SubSection>
          <SubSection number="12.3" title={t.s12_3}>
            <ul className="list-disc ml-6 space-y-2">{t.s12_3items.map((item, i) => <li key={i}>{item}</li>)}</ul>
          </SubSection>
          <SubSection number="12.4" title={t.s12_4}>
            <p>{t.s12_4p}</p>
            <ul className="list-disc ml-6 space-y-2">{t.s12_4items.map((item, i) => <li key={i}>{item}</li>)}</ul>
            <p>{t.s12_4note}</p>
          </SubSection>
          <SubSection number="12.5" title={t.s12_5}><p>{t.s12_5p}</p></SubSection>
          <SubSection number="12.6" title={t.s12_6}><p>{t.s12_6p}</p></SubSection>
          <SubSection number="12.7" title={t.s12_7}><p>{t.s12_7p}</p></SubSection>
          <SubSection number="12.8" title={t.s12_8}><p>{t.s12_8p}</p></SubSection>
          <SubSection number="12.9" title={t.s12_9}><p>{t.s12_9p}</p></SubSection>
        </Section>

        <Section number="13" title={t.s13}><p>{t.s13p}</p></Section>
        <Section number="14" title={t.s14}><p>{t.s14p}</p></Section>
        <Section number="15" title={t.s15}>
          <p>{t.s15p}</p>
          <div className="mt-3 p-4 rounded-xl bg-white/[0.03] border border-white/[0.06]">
            <p className="text-gray-300 font-medium">support@reelmotion.ai</p>
            <p className="text-gray-500 text-sm mt-1">Reel Me In Media Limited, London, United Kingdom</p>
          </div>
        </Section>

        <div className="mt-16 p-6 rounded-2xl border border-white/[0.06] bg-white/[0.02] text-center">
          <p className="text-gray-500 text-sm">{t.footer}</p>
        </div>
      </div>
    </div>
  );
}
