// Bilingual copy for the Developer Console. Self-contained like the other
// developer pages (translations.js only carries the sidebar label).
export const strings = {
  en: {
    eyebrow: "// developers",
    title: "Developer Console",
    subtitle: "Use your Reelmotion tokens from other platforms, scripts or AI assistants (Claude, ChatGPT, Cursor).",
    docs: "Developer docs",
    online: "API · online",
    tiles: { keys: "API keys", apps: "Connected apps", balance: "Token balance" },
    quick: {
      title: "Quick start",
      hint: "Create a key below and it drops straight into these snippets.",
      tabs: { curl: "curl", claude: "Claude Code", cursor: "Cursor", header: "MCP + API key" },
    },
    mcp: {
      title: "Connect an AI assistant",
      url: "MCP URL",
      claude: { name: "Claude", how: "Settings → Connectors → Add custom connector → paste the MCP URL, then sign in." },
      chatgpt: { name: "ChatGPT", how: "Settings → Apps & Connectors → Create (developer mode) → paste the MCP URL with OAuth." },
      cursor: { name: "Cursor", how: "Add the server to .cursor/mcp.json, then authenticate from the MCP panel." },
    },
    tabs: { keys: "API keys", clients: "OAuth apps", apps: "Connected apps" },
    keys: {
      empty: "No API keys yet. Create one to call the REST API.",
      label: "Name (e.g. Zapier, my script)",
      create: "Create key",
      created: "Copy your key now — it will not be shown again.",
      lastUsed: "Last used",
      never: "never",
      created_at: "Created",
      revoke: "Revoke",
      confirm: "Revoke this key? Anything using it will stop working.",
      hint: "Send it as Authorization: Bearer rm_… to https://backend.reelmotion.ai/api/v1/…",
    },
    clients: {
      empty: "Register an OAuth app if you are building a platform where Reelmotion users sign in with their own account.",
      name: "App name",
      redirects: "Redirect URIs (one per line)",
      create: "Register app",
      secret: "Client secret — copy it now, it will not be shown again.",
      rotate: "Rotate secret",
      delete: "Delete",
      confirmDelete: "Delete this app? Every user connection to it will be revoked.",
      clientId: "Client ID",
    },
    apps: {
      empty: "No external apps have access to your account.",
      granted: "Connected",
      lastUsed: "Last used",
      revoke: "Disconnect",
      confirm: "Disconnect this app? It will lose access immediately.",
    },
    scopes: {
      profile: "Read profile & balance",
      billing: "Generate purchase links",
      generate: "Create generations (spends tokens)",
      "tasks:read": "Read generation results",
    },
    copy: "Copy",
    copied: "Copied",
    error: "Something went wrong",
  },
  es: {
    eyebrow: "// developers",
    title: "Consola de desarrollador",
    subtitle: "Usa tus tokens de Reelmotion desde otras plataformas, scripts o asistentes de IA (Claude, ChatGPT, Cursor).",
    docs: "Documentación",
    online: "API · online",
    tiles: { keys: "API keys", apps: "Apps conectadas", balance: "Balance de tokens" },
    quick: {
      title: "Quick start",
      hint: "Crea una key abajo y aparece directo en estos snippets.",
      tabs: { curl: "curl", claude: "Claude Code", cursor: "Cursor", header: "MCP + API key" },
    },
    mcp: {
      title: "Conecta un asistente de IA",
      url: "URL MCP",
      claude: { name: "Claude", how: "Ajustes → Conectores → Agregar conector personalizado → pega la URL MCP e inicia sesión." },
      chatgpt: { name: "ChatGPT", how: "Ajustes → Apps y conectores → Crear (modo desarrollador) → pega la URL MCP con OAuth." },
      cursor: { name: "Cursor", how: "Agrega el server a .cursor/mcp.json y autentica desde el panel MCP." },
    },
    tabs: { keys: "API keys", clients: "Apps OAuth", apps: "Apps conectadas" },
    keys: {
      empty: "Aún no tienes API keys. Crea una para usar la API REST.",
      label: "Nombre (ej. Zapier, mi script)",
      create: "Crear key",
      created: "Copia tu key ahora — no se volverá a mostrar.",
      lastUsed: "Último uso",
      never: "nunca",
      created_at: "Creada",
      revoke: "Revocar",
      confirm: "¿Revocar esta key? Todo lo que la use dejará de funcionar.",
      hint: "Envíala como Authorization: Bearer rm_… a https://backend.reelmotion.ai/api/v1/…",
    },
    clients: {
      empty: "Registra una app OAuth si construyes una plataforma donde los usuarios de Reelmotion inician sesión con su propia cuenta.",
      name: "Nombre de la app",
      redirects: "Redirect URIs (una por línea)",
      create: "Registrar app",
      secret: "Client secret — cópialo ahora, no se volverá a mostrar.",
      rotate: "Rotar secret",
      delete: "Eliminar",
      confirmDelete: "¿Eliminar esta app? Se revocarán todas las conexiones de usuarios.",
      clientId: "Client ID",
    },
    apps: {
      empty: "Ninguna app externa tiene acceso a tu cuenta.",
      granted: "Conectada",
      lastUsed: "Último uso",
      revoke: "Desconectar",
      confirm: "¿Desconectar esta app? Perderá el acceso de inmediato.",
    },
    scopes: {
      profile: "Leer perfil y balance",
      billing: "Generar links de compra",
      generate: "Crear generaciones (gasta tokens)",
      "tasks:read": "Leer resultados",
    },
    copy: "Copiar",
    copied: "Copiado",
    error: "Algo salió mal",
  },
};

export const MCP_URL = `${(import.meta.env.VITE_APP_BACKEND_URL || "").replace(/\/api\/?$/, "")}/mcp`;
